### ISSUE TITLE
Update the sheet with relevant data

### ISSUE THREAD

**Issue by khushpreet-kaur** [janastu/IIHS-TNUSSP-feed#1]
https://docs.google.com/spreadsheets/d/1Q006LR8bMcMy2bKsD172__hzNCoTrX39CMInk9V_mVY/edit#gid=0

**Comment by salus-sage** [comment]
What do you think aboout sending this sheet to IIHS to confirm if the not-working-Links are actually required for them or not?

**Comment by khushpreet-kaur** [comment]
Good idea, we can do that.  
Or we can also try updating the latest links, if we find any.  And then get it confirmed from them for the rest with `not working` status?

**Comment by salus-sage** [comment]
i guess we have moved ahead from pre-phase1 milestone and this issue is not relevant anymore.
