### ISSUE TITLE
iihs_sources_v3 - Deccan herald - Incorrect RSS link

### ISSUE THREAD

**Issue by salus-sage** [janastu/IIHS-TNUSSP-feed#13]
The root html page is configured, which is not correct as per testcase 3 mentioned in issue #5 
incorrect - http://www.deccanherald.com/rss.html
correct - http://www.deccanherald.com/rss-internal/sunday.rss

**Comment by khushpreet-kaur** [comment]
Replace old links with latest ones in sources_v3 on newsrack.

**Comment by salus-sage** [comment]
Did u update all categories

**Comment by khushpreet-kaur** [comment]
@salus-sage  Yes. All categories.

**Comment by salus-sage** [comment]
issue resolved
