### ISSUE TITLE
iihs_sources_v3: Asian age - insufficient source

### ISSUE THREAD

**Issue by salus-sage** [janastu/IIHS-TNUSSP-feed#14]
Asian age has official feeds, if you do view page source you will find the pattern. 
ex: AsianAge:home - http://www.asianage.com/rss_feed/
AsianAge:India - http://www.asianage.com/rss_feed/?sectionId=36
AsianAge:Metros - http://www.asianage.com/rss_feed/?sectionId=52

please update official links for this source

**Comment by khushpreet-kaur** [comment]
@salus-sage Updated sources_v3 with official rss links on newsrack.

**Comment by salus-sage** [comment]
issue resolved
