### ISSUE TITLE
IIHS_sources_v3: Thestatesman is missing

### ISSUE THREAD

**Issue by salus-sage** [janastu/IIHS-TNUSSP-feed#15]
The statesman.com is missing from the latest sources config in Newsrack
They got official rss, links are as below

http://thestatesman.com/rss/home/
http://www.thestatesman.com/rss/india
and so on for other categories

**Comment by khushpreet-kaur** [comment]
Official rss links has been updated for this in sources_v3.

**Comment by salus-sage** [comment]
issue resolved
