### ISSUE TITLE
iihs_sources_v3: TOI all sources and categories may not be defined, hence showing up in missed articles

### ISSUE THREAD

**Issue by salus-sage** [janastu/IIHS-TNUSSP-feed#17]
All rss links from this page should go into the Newsrack sources file
http://timesofindia.indiatimes.com/rss.cms

example of missing urls
http://timesofindia.indiatimes.com/rssfeedstopstories.cms

http://timesofindia.indiatimes.com/rssfeeds/1221656.cms
http://timesofindia.indiatimes.com/rssfeeds/296589292.cms
http://timesofindia.indiatimes.com/rssfeeds/7098551.cms
http://timesofindia.indiatimes.com/rssfeeds/1898055.cms
http://timesofindia.indiatimes.com/rssfeeds/3908999.cms
http://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms
http://timesofindia.indiatimes.com/rssfeeds/2647163.cms

**Comment by khushpreet-kaur** [comment]
Refer to #16   Should be similar solution.

**Comment by khushpreet-kaur** [comment]
#18

**Comment by khushpreet-kaur** [comment]
@salus-sage  Official rss link for all the categories are updated in sources_v3 on newsrack. Please verify.

**Comment by salus-sage** [comment]
all urls configured, this source should not be showing up in missed articles anymore. issue resolved
