### ISSUE TITLE
iihs_sources_v3: Navhind times -  Incorrect feed url

### ISSUE THREAD

**Issue by salus-sage** [janastu/IIHS-TNUSSP-feed#19]
incorrect: http://www.navhindtimes.in/?format=feed&type=rss
correct: 
http://www.navhindtimes.in/feed/
http://www.navhindtimes.in/category/nationalnews/feed/
http://www.navhindtimes.in/category/goanews/feed/
and so on...

**Comment by khushpreet-kaur** [comment]
Updated latest urls for all the categories in sources_v3 on newsrack.

**Comment by salus-sage** [comment]
issue resolved
