### ISSUE TITLE
Time of feeds generated in Newsrack

### ISSUE THREAD

**Issue by tnussp** [janastu/IIHS-TNUSSP-feed#27]
Hi,
Can you please clarify, the time of the feeds that are reflected in the Newsrack. Because, when I check for feeds in water (tamil) category, for today’s date, there is only one feed generated. whereas, if I search in google news for குடிநீர் keyword, there are a number of news related to it. thanks.

**Comment by salus-sage** [comment]
Please document the news showing in Google as "missed article" in the testing report, so that we can review. It can be for many reasons and we need to analyse.

**Comment by tnussp** [comment]
okay. thanks.
