### ISSUE TITLE
Test case1: main_category (.xml) link

### ISSUE THREAD

**Issue by khushpreet-kaur** [janastu/IIHS-TNUSSP-feed#4]
`main_category` (`.xml`) link (like sports, health, business, world etc in one main category)

**Issue definition in Newsrack:**  

```
define sources {gen_news}
	timesofindia = "TimesOfIndia", http://timesofindia.indiatimes.com/rssfeeds/296589292.cms
end sources

define concepts
   <water> = water, drinking water
   <politics> = Narendra Modi, BJP, AAP, Mamata Banerjee, politicians, elections
   <sports> = cricket, football, MS Dhoni, captaincy
   <pot> = pot, medical use, marijuana
end concepts

define issue usecase1-world-category-xml-link-toi
  monitor sources {gen_news} organize news into categories
  {
    [Water] = water
    [politics] = politics
    [sports] = sports
    [pot] = pot
  }
end issue

```

**News Source format:**  `.xml` for "World News Headlines, Latest International News, World Breaking News  category - Times of India"

**Concepts:** Water, politics, sports, cricket, pot etc. 
 
**Expected result:**  Get news feed based on `concepts` as a keyword from the `source` provided. 

**Actual Result:**  As expected result.  Got [7] feed for "pot[1]", "politics[2]", "water[4]", sports[0]" 

**Status:** PASS 

**Source format Validation Status:** VALID  (`.xml` with any category)

**Comment by salus-sage** [comment]
we should extend the keywords for pot, for personal following ;) 
keywords: ganja, charas, hash, cream, weed, chillum, buds...
