### ISSUE TITLE
Testcase4. import All Indian news from newsrack's library.

### ISSUE THREAD

**Issue by khushpreet-kaur** [janastu/IIHS-TNUSSP-feed#6]
import `Sources` from library. 

**Issue definition in Newsrack:**  

```
import sources {Indian News Media Feeds} from library
import sources {rss.feeds} from subbu

define concepts
   <water> = water, drinking water
   <politics> = Narendra Modi, BJP, AAP, Mamata Banerjee, politicians, elections
   <sports> = cricket, football, MS Dhoni, captaincy
   <pot> = pot, marijuana, medical use
end concepts

define issue usecase4-indian-news-from-library
  monitor sources {Indian News Media Feeds} organize news into categories
  {
    [Water] = water
    [politics] = politics
    [sports] = sports
    [pot] = pot
  }
end issue

```

**News Source format:**   import sources from Newsrack's Library. 

**Concepts:** Water, politics, sports, cricket, pot etc. 
 
**Expected result:**  To get news feed based on `concepts` as a keyword from the `source` provided. 

**Actual Result:**  As expected. Got  [3,165] feed. 

**Status:** PASS

**Source format Validation Status:**  VALID

**Comment by salus-sage** [comment]
Out of this Library we should find out which sources have bad links. We should be able to identify and changes these sources.
