### ISSUE TITLE
Create a Indian news library for IIHS feed 

### ISSUE THREAD

**Issue by khushpreet-kaur** [janastu/IIHS-TNUSSP-feed#7]
A library need to be created.  Which can be used/import while defining source for `Newrack's issue`,  to get the feeds based on defined `concepts`.

**Comment by salus-sage** [comment]
So the name space for this library will be IIHS_Sources

**Comment by khushpreet-kaur** [comment]
@salus-sage 

Phase1:  [DONE] Library has been created and tested with 10 English news sources, shared by IIHS over mail. 

Phase2: [TODO] All the 43 English news sources and 10 English magazine sources should be updated in 'IIHS_Sources' libarary, as per contract.

**Comment by khushpreet-kaur** [comment]
@salus-sage  Phase 2 souce config is done. Library is updated with all the English news and magazine sources on newsrack.  Check the configured sources [here](https://github.com/janastu/IIHS-TNUSSP-feed/blob/master/iihs_sources-v3.txt)
